project: 
  type: website
  output-dir: docs

website: 
  title: Real-Time Analytics
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Lectures"
        contents:
        - lecture1.qmd
        - lecture2.qmd
        - lecture3.qmd
        - lecture4.qmd
      - section: "Laboratories"
        contents: 
        - lab/lab1.ipynb
        - lab/lab2.ipynb
        - lab/lab3.ipynb
  navbar:
    left: 
          - href: index.qmd
            text: Home
          - href: sylabus.qmd
            text: Syllabus
          - href: info.qmd
            text: Tools
          - href: books.qmd
            text: Books
          

format:
  html:
    light: cosmo
    css: style.css
    toc: true
    self-contained-math: true