---
title: "Info"
---

## Real Time Analytics 

Kod: 222891-D

Winter semester 2022/2023,
SGH Warsaw School of Economics


Basics information about this course can be found in the [syllabus](/sylabus).

List of [books](/books)! I recommend.

If You don't know what Python is go [here](/info).

## Schedule

#### Lectures

Lectures are OPTIONAL and takes place in G-208.

1. <del>26-02-2024 (Monday) 08:00-9:30 - Lecture 1</del>

The lecture covers:

- Introduction informations,
- structured and unstructured data, 
- introduction to Big Data, 
- data generation processes, 
- OLTP vs OLAP 

2. <del>04-03-2024 (Monday) 08:00-9:30 - Lecture 2</del>

The lecture covers:
- Time for buisnees decision,
- ETL, ELT and MapReduce, 
- Events and stream data definitions 

3. <del>11-03-2024 (Monday) 08:00-9:30 - Lecture 3</del>

4. <del>18-03-2024 (Monday) 08:00-9:30 - Lecture 4</del>

5. 18-03-2024 (Monday) 08:00-9:30 - Lecture 5

Lectures end with a TEST: 20 questions - 30 minutes.

The test will be conducted using MS Teams.

#### Labs

1. 09-04-2024 (Tuesday) 9:50-11:30 - C2B 
2. 16-04-2024 (Tuesday) 9:50-11:30 - C2B
3. 23-04-2024 (Tuesday) 9:50-11:30 - C2B 
4. 30-04-2024 (Tuesday) 9:50-11:30 - C2B 
5. 07-05-2024 (Tuesday) 9:50-11:30 - C2B 
6. 14-05-2024 (Tuesday) 9:50-11:30 - C2B 
7. 21-05-2024 (Tuesday) 9:50-11:30 - C2B 
8. 28-05-2024 (Tuesday) 9:50-11:30 - C2B 
9. 04-06-2023 (Tuesday) 9:50-11:30 - C2B

#### Place

Lectures 1-4: G-208
Labs 1-10: C-2B

#### Exam

The lectures will conclude with a test on the last day of class.
If you score above 13 points on the test, you will be eligible to carry out the exercises.

Once you have completed the exercises, you will need to submit your homework through the MS Teams platform.
 If you pass all the exercises and tasks, you will be allowed to complete the project.

You can work on the project in groups of up to five people. Here are the requirements for the project:

- Your project must address a BUSINESS PROBLEM that can be implemented using online information. You can use batch processing, such as generating a model, if needed.
- You must send data to Apache Kafka for further processing and analysis.
- You can use any programming language for your project components.
- BI tools are allowed.
- Your data sources can include tables, artificially generated data, IoT, and more.

## Technology

Participating in the classes, you must know and at least use the following information technologies:

1. [GIT](https://sebkaz-teaching.github.io/RTA_2023EN/info/) 
2. Python, Jupyter notebook
3. [Docker](https://sebkaz-teaching.github.io/RTA_2023EN/info/)
4. **Apache Spark**, Apache Flink, **Apache Kafka**.